### ISSUE TITLE
Fix error: SyntaxError: "undefined" is not valid JSON

### ISSUE THREAD

**Issue by Miguiz** [multiversx/mx-sdk-js-network-providers#68]
https://github.com/multiversx/mx-sdk-js-network-providers/blob/6626d45ef6b0d395ab62eb66dd03bb2d7394ac94/src/apiNetworkProvider.ts#L38

SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at ApiNetworkProvider.getProxyConfig (/node_modules/@multiversx/sdk-network-providers/src/apiNetworkProvider.ts:39:32)
    at new ApiNetworkProvider (/node_modules/@multiversx/sdk-network-providers/src/apiNetworkProvider.ts:32:32)

Change this:
```ts
    private getProxyConfig(config: NetworkProviderConfig | undefined) {
        let proxyConfig = JSON.parse(JSON.stringify(config));
        proxyConfig = { ...defaultAxiosConfig, ...proxyConfig };
        return proxyConfig;
    }
```
to this please:
```ts
    private getProxyConfig(config: NetworkProviderConfig | undefined) {
        let proxyConfig = JSON.parse(JSON.stringify(config ?? {}));
        proxyConfig = { ...defaultAxiosConfig, ...proxyConfig };
        return proxyConfig;
    }
```

**Comment by andreibancioiu** [comment]
Thank you for reporting the issue :pray: 

Will be handled in https://github.com/multiversx/mx-sdk-js-network-providers/pull/69.
